### ISSUE TITLE
Cross Compatibility bug with Matter Overdrive Mod

### ISSUE THREAD

**Issue by NullMagic** [tschallacka/MagicCookies#1]
There appears to be an issue with this mod and Matter Overdrive, I posted the crash report to a bug there already (https://github.com/simeonradivoev/MatterOverdrive/issues/136), it'd be awesome if you could get together with the devs of that mod and figure out what the problem is.

The crash report, for reference: http://pastebin.com/CeK4Vtnt

**Comment by tschallacka** [comment]
Hmmh, I'm gonna look into it. i'm close to releasing a small update with patches and stuff, I'll take this along too in Magic Cookies. And yea, I forgot an instanceof check, but looking at the code, it shouldn't have supplied it...

But, then again, someone has been hitting the grog and gotten drunk... so badly he crashed :-P

I'll add a check :-) and hopefully this will be resolved then.

Btw, congrats, you're the first outside of my server who has reported a bug to me :-)

**Comment by NullMagic** [comment]
It's no problem, and honestly is probably obscure enough that if I hadn't shoved it into a pack with 260 other mods it likely would never have been noticed.

**Comment by tschallacka** [comment]
This problem will be fixed in the next release, but that mod does some iffy stuff with it's androids.
It's calling player only render code, and since it's not a player Entity/doesn't have all the needed properties which is actually passed to the code in question it fails hard.
I have added a typecheck which should resolve it, but in all honestly, this shouldn't have happened or been requested this way.
